import { IAiAdapter } from './ai-adapter.js';

export class MockAdapter implements IAiAdapter {
  isReal(): boolean {
    return false;
  }

  async generate(prompt: string): Promise<string> {
    return [
      '# GitHub Copilot Prompt — Generated by r2pde-ai (Mock Mode)',
      '',
      '> ⚠ This prompt was generated in offline mode (no AI API configured).',
      '> Configure ai.apiUrl and ai.apiKey for AI-optimized prompts.',
      '> To configure: r2pde-ai config:set ai.apiUrl <url>',
      '> To configure: r2pde-ai config:set ai.apiKey <key>',
      '',
      '---',
      '',
      '## Instructions for GitHub Copilot',
      '',
      'Read the full context below and implement the requested wave.',
      'Follow all manifests, contracts, and requirements strictly.',
      'Generate production-ready TypeScript code only.',
      'Do not ask questions — implement based on the context provided.',
      '',
      '---',
      '',
      prompt,
    ].join('\n');
  }
}
